### ISSUE TITLE
两个不同的人脸测试发现相似度是0.9560

### ISSUE THREAD

**Issue by cayden** [vcvycy/Android_Facenet#2]
Hi,打扰了，想咨询一下我在用demo测试发现找了2个不同的人脸，测试的相似度为0.9560 小于1.1了。出现这种情况会是哪个地方设置问题呢，谢谢！

**Comment by vcvycy** [comment]
按照具体需求设置阈值即可。
google测试用的阈值是1.204，这个数值是为了在数据集上得到最高的精度。
但是具体应用时，这个值就不是很合适：
(1) 明显不同的两个人，相似度一般为1.4左右
(2) 明显相同的2个人，相似度一般为0.6左右
(3) 介于二者之间的，看具体需求，设置得小点可以降低False Postive的值；
     比如设置为0.8这样。

**Comment by cayden** [comment]
好的。谢谢回复！
