### ISSUE TITLE
我有个疑问，为什么不用facenet提供的预训练模型呢

### ISSUE THREAD

**Issue by mmabluesky** [vcvycy/Android_Facenet#4]

**Comment by mmabluesky** [comment]
facenet的预训练模型，pb被我转成了tflite，准备用tensorflow lite加载模型的， 看你的demo，却是加载mtcnn_freezed_model.pb，为何这样做呢，

**Comment by Desolve** [comment]
作者這個的作法是沒有用到tensorflow lite的，他是用tensorflow android。
按我的理解，mtcnn的加載用意是為了將兩張圖中的臉部框出來，
再用facenet將框出來的兩張臉提取特徵值做比對。
(MainActivity中的Line 99, 100
FaceFeature ff1=facenet.recognizeImage(face1);
 FaceFeature ff2=facenet.recognizeImage(face2);)
(對應到Facenet.java中的recognizeImage，是使用facenet預訓練的.pb檔來inference的)

(當然如果一開始就已經確定你給的圖必然是只有臉部的話，應該可以直接用facenet)

樓主，能順帶問下pb轉tflite的環境和具體操作嗎?我之前試著轉過沒有成功，希望可以教下。

**Comment by mmabluesky** [comment]
@Desolve 
pb转lite见https://github.com/jiangxiluning/facenet_mtcnn_to_mobile

**Comment by Desolve** [comment]
@mmabluesky facenet是臉部識別(face recognition)而非臉部檢測(face detection)，
後者著重在將人臉抓出來(如mtcnn)，前者著重在判斷不同臉部圖片的相似程度。
所以論文中也大多在談所有已給定的人臉的比較狀況。
[FaceNet: A Unified Embedding for Face Recognition and Clustering](https://arxiv.org/abs/1503.03832)

**Comment by Desolve** [comment]
兩者加起來APK大小大約1XX MB上下。

**Comment by mmabluesky** [comment]
@Desolve 
对tensorflow lite熟悉吗？  我生成了facenet.tflite，但是我没有标签文件lable.txt， 那我应该怎么用tf lite加载模型呢
